### ISSUE TITLE
Direct3D 11 UWP Template fails WACK Prelaunch tests

### ISSUE THREAD

**Issue by stammen** [walbourn/directx-vs-templates#1]
How to repro:

1) Create a new VS2015 project using the Direct3D UWP Game template
2) Create a store package and run the WACK Prelaunch test

Result:

Deployment and launch tests using WACK 10.0

FAILED
App prelaunch
Error Found: The app prelaunch validation detected the following errors:
The app failed prelaunch test - c06fbd2c-afed-49e9-ac00-37a11a7ce589_1.0.1.0_x86__m9k0q4hvj1fvp.
Impact if not fixed: The app will take a longer time to launch, even when prelaunch is enabled.
How to fix: In the OnLaunched method implementation of the app, ensure you handle the LaunchActivatedEventArgs.PreLaunch option to be prelaunch event aware.

**Comment by stammen** [comment]
The issue appears to be CoreApplication::Exit(); According to [msdn](https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.core.coreapplication.exit.aspx) this call should not be made by a published app. 

[MSDN](https://msdn.microsoft.com/en-us/library/windows/apps/mt593297.aspx) guidance for opting out of prelaunch says to simply return from OnLaunched() before doing any work to create a frame or activate the window.

Is it okay to simply remove the call to Exit(). The template passes the WACK Prelaunch test without the call to Exit().

**Comment by walbourn** [comment]
Prelaunch is a very problematic feature for games, and for "DirectX apps" calling Exit is the only way to 'opt-out'. For "DirectX+XAML apps" it's a little easier to opt-out.

The WACK test is going to be changed here.

**Comment by stammen** [comment]
@walbourn Thanks for the update.
