### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by joneschrisan** [walbourn/directx-vs-templates#14]
When creating a new monogame UWP in VS 2017 you now get a new error. 

--------------------------
Package Installation Error

Could not add all required packages to the project. The following packages failed to install from 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages':

Microsoft.NETCore.UniversalWindowsPlatform.5.1.0 : Unable to find version '5.1.0' of package 'Microsoft.NETCore.UniversalWindowsPlatform'.
--------------------------

After clicking the only option "OK" You still have the errors as before but build always fails

**Comment by walbourn** [comment]
Sorry, but this GitHub project isn't related to the MonoGame project. You should file this issue [here](https://github.com/MonoGame/MonoGame) instead
