### ISSUE TITLE
DR needs support for "CreateSwapChainForComposition"

### ISSUE THREAD

**Issue by HppZ** [walbourn/directx-vs-templates#18]

**Comment by walbourn** [comment]
Generally for these templates I do not support XAML scenarios. Those are covered by the standard "DirectX App" templates that come with Visual Studio, and are out-of-scope for my deved efforts.

For DX12, there was a partially completed DirectX 12 + XAML template [here](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/feature_xaml_template/Templates), but I don't believe it was ever completed.
