### ISSUE TITLE
Toggling fullscreen to windowed produces an error beep sound

### ISSUE THREAD

**Issue by awangk** [walbourn/directx-vs-templates#2]
Happens with Direct3D Win32 Game and  Direct3D12 Win32 Game.  Not sure what is causing the beep.

**Comment by walbourn** [comment]
Do you have a multi-monitor setup? It appears to do that when the window is adjusted to fit into the bounds of the monitor (i.e. it briefly returns to a position outside the monitor area and then gets moved to fit).

**Comment by walbourn** [comment]
Ah, I found it... in DXUT we had this in the proc:

        case WM_MENUCHAR:
            // A menu is active and the user presses a key that does not correspond to any mnemonic or accelerator key
            // So just ignore and don't beep
            return MAKELRESULT( 0, MNC_CLOSE );

**Comment by walbourn** [comment]
Fixed.
