### ISSUE TITLE
Rendering at the beginning does not show correctly.

### ISSUE THREAD

**Issue by HppZ** [walbourn/directx-vs-templates#21]
I create a DirectX11 App (Windows Universal) project using Visual Studio 15.9.2 and hit a breakpoint at the end of function `Render` in file "SampleFpsTextRenderer.cpp", then I run that project, but the text does not show up correctly at the bottom right corner in the first time.
![qq 20181128140326](https://user-images.githubusercontent.com/12285582/49132559-d0f03280-f317-11e8-8c9d-ca0e070ccaee.png)

OS: 17134.407

**Comment by HppZ** [comment]
change some rendering config, then it works fine:

Translation:
`D2D1::Matrix3x2F screenTranslation = D2D1::Matrix3x2F::Translation(
		logicalSize.Width - m_textMetrics.width,
		logicalSize.Height - m_textMetrics.height
		);`

and SetTextAlignment:
`m_textFormat->SetTextAlignment(DWRITE_TEXT_ALIGNMENT_LEADING)
`

**Comment by walbourn** [comment]
First, that's not one of my templates. Those are the built-in VS templates for DirectX UWP apps. My templates do not include the **SampleFpsTextRenderer** code as well as a number of other differences. As such, you should look to more general DirectX / UWP help forums such as the [MSDN Forums](https://social.msdn.microsoft.com/Forums/en-US/home) for support.

The FPS value comes from the [StepTimer class](https://github.com/Microsoft/DirectXTK/wiki/StepTimer
), and it won't have a value the first frame or even the first several frames. It takes a snapshot once per second, so it's not an instantaneous value. Wait a 30 - 60 frames or more and it will have a value.

**Comment by HppZ** [comment]
I do not mean the FPS value, I mean the position of it.

**Comment by walbourn** [comment]
My templates don't use Direct2D either. Best bet is [MSDN Forums: Developing Universal Windows apps](https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop&filter=alllanguages)

**Comment by HppZ** [comment]
OK Thanks. 
I think the problem is solved.
Good day.
