### ISSUE TITLE
Flicker when resizing window

### ISSUE THREAD

**Issue by awangk** [walbourn/directx-vs-templates#22]
In the Win32 template when resizing the window by dragging the corner the white window background can be seen in the lower left corner.  This is most clearly visible when quickly making the window smaller.

The sample is using DXGI_SCALING_STRETCH, but I don't think the issue is D3D, but rather that window messages that repaint the NC area lags behind.

**Comment by walbourn** [comment]
For performance reasons, I specifically do not resize the backbuffer during the 'rubberbanding' resize (this is done by monitoring ``WM_ENTERSIZEMOVE`` / ``WM_EXITSIZEMOVE`` messages. Therefore, while in a move, the game is 'ticked' during ``WM_PAINT`` to keep rendering to the same back buffer size.

How that is rendered depends on the OS version. Which OS and service pack/build are you using?

**Comment by awangk** [comment]
17763.379

So I noticed that the D3D11 Win32 template does not have this issue and that seems to be b/c the swap chain is using discard rather flip_discard.

The D3D12 version is using DXGI_SWAP_EFFECT_FLIP_DISCARD.  If I change the D3D11 version to DXGI_SWAP_EFFECT_FLIP_DISCARD I get the exact same flaky resizing behavior where the HWND's white background HBRUSH shows when the window resized to be smaller.

**Comment by awangk** [comment]
So my question is: Is this a bug or limitation in Windows 10 or is it possible to work around it and get the same smooth resizing behavior in d3d12 as in d3d11?

**Comment by walbourn** [comment]
It's not possible to use the older swap-styles with DirectX 12 in any case.

I don't think there's really anything that can be done by the app. The problem repros on Windows 10 (18362) as well, so you should report it as a bug with the new flip effects.
