### ISSUE TITLE
d3d11game_uwp_* and d3d12game_uwp_*.vstemplate files have the same TemplateId value

### ISSUE THREAD

**Issue by ImJustStokedToBeHere** [walbourn/directx-vs-templates#24]
This seems to be causing the d3d11* templates to be excluded from list on the "New Project" dialog in vs2019 community.

**Comment by walbourn** [comment]
Alas in the VS 2019 New Project dialog, there's no current way to have 3rd party VSIX files appear in the proper categories. They can only be found by search.

None of the new tagging system uses existing ``.vstemplate`` elements.

**Comment by walbourn** [comment]
FWIW, I updated the IDs for the 12 projects in [this commit](https://github.com/walbourn/directx-vs-templates/commit/885810ed9c78c9656687dfe54281f8e30c09defe).

**Comment by walbourn** [comment]
For VS 2019 Update 1, they fixed the problem of 3rd party VSIX packages not being able to be tagged for the new project dialog. See [this blog post](https://devblogs.microsoft.com/visualstudio/build-visual-studio-templates-with-tags-for-efficient-user-search-and-grouping/).
