### ISSUE TITLE
Nuget package for C++/WinRT 2.0?

### ISSUE THREAD

**Issue by johanlindfors** [walbourn/directx-vs-templates#25]
The latest version of C++/WinRT should have the Nuget package integrated. Is that something we can help with?

**Comment by walbourn** [comment]
This site just hosts a few templates for C++/WinRT related to my GitHub projects. It's not for the official [NuGet](https://www.nuget.org/packages/Microsoft.Windows.CppWinRT/) or [VSIX](https://marketplace.visualstudio.com/items?itemName =CppWinRTTeam.cppwinrt101804264) packages.

What issue are you trying to report?

**Comment by johanlindfors** [comment]
Well, since 2.0 of C++/WinRT we are supposed to reference that NuGet package to instead of leveraging the winrt headers included in the Windows SDK, let the cppwinrt compiler generate the headers for each projects.

Mentioned here: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/news

**Comment by johanlindfors** [comment]
I created a small PR draft #26 to demonstrate the suggestion.

**Comment by walbourn** [comment]
You can create an instance of one of the UWP C++/WinRT projects in this GitHub's VSIX and they build fine with the Windows 10 SDK (17763 or later) even if you are not using any NuGet packages.

If you want to use the new C++/WinRT 2.0 generator solution, you can add the ``Microsoft.Windows.CppWinRT`` NuGet package to your project and it will use that instead.

That said, you need a fix to Main.cpp from [this commit](https://github.com/walbourn/directx-vs-templates/commit/da1191f2f49b2382262255336dbfe9f875323895). I'll do a new VSIX tomorrow to include the most recent fixes.

**Comment by walbourn** [comment]
The ``Microsoft.VisualStudio.WinRT.TemplateWizards`` issue you mention sounds like a possible return of an old problem in VC that was missing the remaps for older versions of the VSIX components. Do you have the "UWP" workload for VS 2019 installed?

**Comment by johanlindfors** [comment]
I though I had, since I pretty much ONLY do UWP development with VS2019...

Will investigate further. Thx!

**Comment by walbourn** [comment]
I had an issue with VS 2017 that was fixed in 15.3 that provided redirect bindings:

**Comment by walbourn** [comment]
Do you have VS 2017 and VS 2019 on the machine that's failing, or just VS 2019?

**Comment by johanlindfors** [comment]
Both...

**Comment by walbourn** [comment]
Hmmm. It works for me, but I have VS 2015 installed too... Can you file an issue with the VS "File a problem..." feature for the "14.0.0.0" warning? I can then point the PM to that bug.

**Comment by walbourn** [comment]
I released the updated [VSIX](https://github.com/walbourn/directx-vs-templates/releases/tag/may2019) with the Main.cpp compatible with C++/WinRT 2.0.

**Comment by walbourn** [comment]
So the redirects are already present, so that's not the issue in ``devenv.exe.config``:

```
        <!-- Redirects for Universal app template wizard assemblies -->
        <!-- This is to allow VS 2015 and VS 2017 project templates to work correctly in VS 2019 -->
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.Universal.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0" newVersion="16.0.0.0"/>
          <bindingRedirect oldVersion="15.0.0.0" newVersion="16.0.0.0"/>
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.WinRT.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0" newVersion="16.0.0.0"/>
          <bindingRedirect oldVersion="15.0.0.0" newVersion="16.0.0.0"/>
        </dependentAssembly>
```

**Comment by walbourn** [comment]
Can you find the file ``Microsoft.VisualStudio.WinRT.TemplateWizards.dll`` on the impacted system? Mine is located here: ``C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\PrivateAssemblies``

    Microsoft.VisualStudio.WinRT.TemplateWizards.dll

**Comment by walbourn** [comment]
And thanks a lot for the VS bug and help in digging in. Good catch for sure. I never noticed it because I had VS 2015 installed in most cases, but I was able to repro it on my laptop with just VS 2017 + VS 2019.

**Comment by walbourn** [comment]
The workaround is:

```
        <!-- Redirects for Universal app template wizard assemblies -->
        <!-- This is to allow VS 2015 and VS 2017 project templates to work correctly in VS 2019 -->
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.Universal.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0-15.0.0.0" newVersion="16.0.0.0"/>
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.WinRT.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0-15.0.0.0" newVersion="16.0.0.0"/>
        </dependentAssembly>
```
