### ISSUE TITLE
Mismatch for the D3D11Device between the private member and the Accessor?

### ISSUE THREAD

**Issue by BMarques** [walbourn/directx-vs-templates#28]
Hello,
While studying the DeviceResources header file present on the d3d11game_uwp_cppwinrt_dr project, I noticed that the private member has:
Microsoft::WRL::ComPtr<**ID3D11Device3**>  m_d3dDevice; 

But the accessor has:
**ID3D11Device2***   GetD3DDevice() const  { return m_d3dDevice.Get(); }

Was that on purpose? If so, why?

Thank you.

**Comment by walbourn** [comment]
Just a copy & paste error moving between the various versions of DR. Fixed in [this commit](https://github.com/walbourn/directx-vs-templates/commit/f05b3098aba72b4da751a54b096b8ea7bcbad242)

**Comment by walbourn** [comment]
Note that for my DX11 PC templates., I assume Windows 7 SP1+DirectX 11.1 runtime. For UWP templates, I assume Windows 10 which was DirectX 11.3 / DirectX 12.0.
