### ISSUE TITLE
DirectX 11 UWP DeviceResources::GetHardwareAdapter selects an invalid adapter when using Debug > Graphics

### ISSUE THREAD

**Issue by trojanfoe** [walbourn/directx-vs-templates#29]
I have noticed that when running a graphics debug session (Debug > Graphics > Start Graphics Debugging) that the following code (in `DeviceResources::GetHardwareAdapter()`) path results in `adapter` being unset and hence crashing:

```
for (UINT adapterIndex = 0;
			 DXGI_ERROR_NOT_FOUND != factory6->EnumAdapterByGpuPreference(adapterIndex,
			 DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,
			 IID_PPV_ARGS(adapter.ReleaseAndGetAddressOf()));
			 adapterIndex++)
		{
			DXGI_ADAPTER_DESC1 desc;
			adapter->GetDesc1(&desc);

```

If I test `adapter` for `null` and `break`, I end up with the WARP driver, however the graphics debug session does work.

I can only assume that `EnumAdapterByGpuPreference()` is returning something other than `DXGI_ERROR_NOT_FOUND` when a capture device is being used.

By restructuring the code so that the `EnumAdapters1()` iteration is called if `adapter` is unset, instead of being in the `else` clause, I get a non-WARP device and debugging works. 

I am using the latest VS templates (as of yesterday) under Windows 10 17763 using the VS2019 (16.1.0) x64.  I have also see this happen under VS2017 (latest) on a different machine.

Here is my final code (with local changes), however you can almost certainly do a better job:
```
void DeviceResources::GetHardwareAdapter(IDXGIAdapter1** ppAdapter)
{
	*ppAdapter = nullptr;

	ComPtr<IDXGIAdapter1> adapter;

#if defined(__dxgi1_6_h__) && defined(NTDDI_WIN10_RS4)
	ComPtr<IDXGIFactory6> factory6;
	HRESULT hr = m_dxgiFactory.As(&factory6);
	if (SUCCEEDED(hr))
	{
		for (UINT adapterIndex = 0;
			 factory6->EnumAdapterByGpuPreference(adapterIndex,
			 DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,
			 IID_PPV_ARGS(adapter.ReleaseAndGetAddressOf())) != DXGI_ERROR_NOT_FOUND;
			 adapterIndex++)
		{
			if (!adapter)
			{
				break;
			}

			DXGI_ADAPTER_DESC1 desc;
			adapter->GetDesc1(&desc);

			if (desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)
			{
				// Don't select the Basic Render Driver adapter.
				continue;
			}
			break;
		}
	}
#endif

	if (!adapter)
	{
		for (UINT adapterIndex = 0;
			 DXGI_ERROR_NOT_FOUND != m_dxgiFactory->EnumAdapters1(adapterIndex, adapter.ReleaseAndGetAddressOf());
			 adapterIndex++)
		{
			DXGI_ADAPTER_DESC1 desc;
			adapter->GetDesc1(&desc);

			if (desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)
			{
				// Don't select the Basic Render Driver adapter.
				continue;
			}

			break;
		}
	}

	*ppAdapter = adapter.Detach();
}

```

**Comment by trojanfoe** [comment]
It appears to be returning 0x80004005 (E_FAIL).

**Comment by walbourn** [comment]
See [this pull request](https://github.com/walbourn/directx-vs-templates/pull/30)

**Comment by walbourn** [comment]
Note the underlying issue is fixed in Windows 10 May 2019 update.
