### ISSUE TITLE
Missing templates with XAML

### ISSUE THREAD

**Issue by heriberto-delgado** [walbourn/directx-vs-templates#31]
Where are the template projects that combine XAML with Direct3D? I can't find any, and VS documentation for them is really poor.

**Comment by walbourn** [comment]
The XAML templates are part of Visual Studio when you install the "UWP" workload and select the optional component "C++ Tools for UWP".

You might want to look at the additional C++/WinRT templates as well. See [here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package).

For my purposes, I don't do anything with XAML.
