### ISSUE TITLE
Cannot create DirectX 11 Win32 projects on VS2019 16.2.0

### ISSUE THREAD

**Issue by trojanfoe** [walbourn/directx-vs-templates#32]
When attempting to generate DirectX 11 Win32 projects (with or without DeviceResources) I get an error dialog about the template attempting to use Microsoft.VisualStudio.WinRT.Templates 14.0.0.0 and it not existing.  The remapping does exist in devenv.exe.config however the .dll does not exist in PrivateAssemblies and I cannot see what component is missing.

It's not clear to me why a Win32 template would reference WinRT at all.

**Comment by walbourn** [comment]
It's used for the "Which Windows 10 SDK do you want" wizard...

Do you have the "UWP" workload installed?

**Comment by trojanfoe** [comment]
Yes.  I have all UWP-related components installed that I can see.

One thing I wondered about was that they are installed for MSVC v142, which might not be right if the template is designed for VS2017?

**Comment by walbourn** [comment]
The template should work with VS 2015, VS 2017, and VS 2019.

I reported the bug on [VS Connect](https://developercommunity.visualstudio.com/content/problem/572125/visual-studio-2019-doesnt-handle-14000-assembly-re.html). I know it didn't make Update 1, but sad to see it's still not in Update 2.

**Comment by walbourn** [comment]
Sorry, but apparently this fix missed Update 2. It will be in Update 3. Use the workaround from [VS Connect](https://developercommunity.visualstudio.com/content/problem/572125/visual-studio-2019-doesnt-handle-14000-assembly-re.html).

**Comment by trojanfoe** [comment]
OK thanks Chuck.

**Comment by walbourn** [comment]
This fix is in VS 2019 (16.3). Of course, you still need to install the UWP workload.

**Comment by isral** [comment]
@walbourn 
Can I request non UWP vsix?
I just need Win32.

**Comment by walbourn** [comment]
I use the ``Microsoft.VisualStudio.Universal.TemplateWizards.PlatformVersion.Wizard`` wizard to pick the version of the Windows 10 SDK to use even with the Win32 templates. This requires the UWP workload to install.
