### ISSUE TITLE
Run-Time Check Failure #0 when Graphics Debugging DeviceResources moved to Engine Library

### ISSUE THREAD

**Issue by cpyburn** [walbourn/directx-vs-templates#34]
I moved DeviceResources to a master library so that I could reference it from lots of test projects.  It builds and runs and I have never had any issues until I tried running Graphics Debugging.  I cannot figure this issue out either.  Can you help lead me in the direction of why this Graphics Debugging doesn't work from a reference library?

![Capture](https://user-images.githubusercontent.com/17934438/66504611-1c728180-ea8f-11e9-9e53-29c93a3b063d.PNG)

**Comment by cpyburn** [comment]
if I comment it out and force the software device, it works fine, and that is what I am doing t
![Capture1](https://user-images.githubusercontent.com/17934438/66505039-1f21a680-ea90-11e9-9d30-7a93fbc94212.PNG)
emporarily.

**Comment by walbourn** [comment]
What version of Windows 10 and what version of PIX are you using? ALso, if you just F5 through the exception does it continue?

**Comment by cpyburn** [comment]
10.0.18362.0 and the PIX that is bundled with visual studio 2019 16.2.5.

If I f5 through it, it eventually crashes.

![image](https://user-images.githubusercontent.com/17934438/66531620-05a14e80-ead2-11e9-98c9-4be9ad7a051a.png)

**Comment by cpyburn** [comment]
![Capture4](https://user-images.githubusercontent.com/17934438/66531944-33d35e00-ead3-11e9-9426-a9420471dcbb.PNG)

**Comment by walbourn** [comment]
I know there were some problems with the capturing of DXGI 1.6 interfaces. Instead of using the VS Graphics Diagnostics, since you are using DX12 you should take a look at the latest [PIX](https://devblogs.microsoft.com/pix/) tool.

**Comment by cpyburn** [comment]
So when I tried to use pix, it only accepts 64 bit apps, since all your templates are 32 I had to convert them.  After I converted them I get a very odd behavior with XM_CALLCONV on FXMVECTOR... etc...

![Capture3](https://user-images.githubusercontent.com/17934438/66612594-dfd68100-eb87-11e9-899b-0c527d59c3f6.PNG)

Do you not need XM_CALLCONV on x64?  __fastcall worked fine...

**Comment by walbourn** [comment]
``XM_CALLCONV`` is ``__vectorcall`` for x64 in most cases.

**Comment by cpyburn** [comment]
I don't understand why debugging is giving all the ???, ???, ???, ???.  All I did was create a "Direct3d12 Win32 Game DR" with your template, turn in to x64, and add a test method.

`XMVECTOR XM_CALLCONV Game::Test(FXMVECTOR test)
{
	XMVECTOR bob = test + XMVectorZero();
	return bob;
}`

AND then this...

![Capture](https://user-images.githubusercontent.com/17934438/66701282-4eb6f580-ecc0-11e9-9328-6de665a7c3ff.PNG)

**Comment by cpyburn** [comment]
So I have everything working, even though I think the ???'s are a bug of some kind in 2019 and you should probably look into it.  You can close this if you like, but I do have a couple general questions that I find conflicting information on, I was hoping you could answer them real fast?

Should you use XM_CALLCONV for XMVECTOR returns?
Is it performance wise to change the HLSL files to be row_major so that you don't have to Transpose all the shader matrix values each update or is this so negligible?

**Comment by walbourn** [comment]
For ``XM_CALLCONV``, see the [DirectXMath Programmer's Guide](https://docs.microsoft.com/en-us/windows/win32/dxmath/pg-xnamath-internals#calling-conventions).

Generally speaking the transpose cost on the CPU is negligible, and it saves about one instruction per invocation of the vertex shader. That said, on modern GPUs that doesn't really matter either. Use what you find convienent.

**Comment by walbourn** [comment]
I don't recognize that debug window you are using. If I use the Visual Studio Debug ->Windows -> Registers display and enable SSE, it works fine.

Perhaps that's some extension that doesn't support ``__vectorcall``?
