### ISSUE TITLE
Still Doesn't Load

### ISSUE THREAD

**Issue by aaronstackpole** [walbourn/directx-vs-templates#42]
Using the absolute latest version of Visual Studio 2019, these templates still throw an error when you try to create a project with them. I checked the known issue, it says that it was fixed, but I still get this:
![image](https://user-images.githubusercontent.com/8165121/107975846-52c2e980-6f7e-11eb-8f2f-ace839ae19be.png)
Has been happening for a while, just assumed it would be fixed, but I've updated VS 2019 at least four or five times since I've had this problem, and my entire system has been rebuilt at least once as well.

**Comment by aaronstackpole** [comment]
Another idea, the main reason why I want these templates is just so that I can get the correct settings out of the project properties dialogs and then I merge them into .props files. It would be particularly handy if you'd just put the custom settings into .props files so I can apply them to my own project files that often have additional settings like preprocessor definitions for additional libraries, includes for the WinSocks libraries, and so forth. I actually don't use the templates themselves, I just extract the settings from the properties.

**Comment by walbourn** [comment]
You need to install the "Universal Platform Apps" workload. That provides the missing Windows SDK wizard selector as noted in the README.md.

Note I also have ``CMakeLists.txt`` for the Win32 projects for reference.

**Comment by aaronstackpole** [comment]
The installer claimed that it was installing this workload as a pre-requisite for the VSIX, so there may be an additional prerequisite that is not detected for some reason. Thank you, will try adding the workload manually.

**Comment by walbourn** [comment]
Thanks, I'll see if they moved something in the recent updates...

**Comment by aaronstackpole** [comment]
Confirmed , installing the entire 10.6GB UWP workload solved it ;)

**Comment by aaronstackpole** [comment]
Common.props
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(ProjectDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <WarningLevel>Level4</WarningLevel>
      <FloatingPointModel>Fast</FloatingPointModel>
      <ConformanceMode>true</ConformanceMode>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <PrecompiledHeaderFile>pch.h</PrecompiledHeaderFile>
    </ClCompile>
    <Link>
      <AdditionalDependencies>d3d11.lib;dxgi.lib;dxguid.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Windows</SubSystem>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>`

Release.props
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <LinkIncremental>false</LinkIncremental>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <FunctionLevelLinking>true</FunctionLevelLinking>
    </ClCompile>
    <Link>
      <OptimizeReferences>true</OptimizeReferences>
    </Link>
    <Link>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>`

Debug.props
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>`

**Comment by aaronstackpole** [comment]
Note I turned permissive- on and set language to 17, which is not the template default, otherwise, these are the properties extracted from the Win32 DR template. Using props pages substantially simplifies my solution configurations, would be awesome if you used them as well for the templates.
