### ISSUE TITLE
GraphicsMemory not allocated

### ISSUE THREAD

**Issue by JonBackupRepos** [walbourn/directx-vs-templates#46]
Hi, thanks for the templates, very useful

Just as a suggestion for your DirectX12 UWP WinRT template, maybe include the GraphicsMemory allocation in the Game.Cpp file.  If you do all the https://github.com/microsoft/DirectXTK12/wiki/The-basic-game-loop stuff will just work.  Otherwise, you get a std::logic_error exception...

Jon

**Comment by walbourn** [comment]
The **directx-vs-templates** are used in my *DirectX Tool Kit* tutorials, but I try to keep them independent so you don't strictly need to use my tool kit.

It would be nice to have a template wizard that could ask for some additional configuration information to add opt-in stuff like setting up directx tool kit, but any wizard with UI tends to get really complicated really quickly.

The other option is to just include the graphics memory stuff but leave it commented it out in fresh templates.

**Comment by JonBackupRepos** [comment]
Well, so, the templates get you started fairly quickly with the tutorials.  But when you add some elements to the scene, without graphics memory allocated DX crashes with a really obscured error message.  Maybe add as a comment?

**Comment by walbourn** [comment]
BTW, I have this on my backlog. I'll look at adding the comment.

**Comment by JonBackupRepos** [comment]
Ah, okay, cool
