### ISSUE TITLE
Question on Context Reset

### ISSUE THREAD

**Issue by aaronstackpole** [walbourn/directx-vs-templates#48]
https://github.com/walbourn/directx-vs-templates/blob/781af561d0bb567f3b2dd051be1000c31b5d9b4b/d3d11game_win32/Game.cpp#L223

On and around the above line you're resetting some values on the D3D11DeviceContext object, I've separated the resources and pipelines into two separate classes and a do a full pointer unique_ptr::reset on the device and recreate it. Do you think it would be necessary still to execute these OMSetRenderTargets() and Flush() commands to clear any caches not direct associated with the device and devicecontext objects, or would recreating the objects be sufficent to give us a clean memory surface to rebuild our graphical content on?

**Comment by walbourn** [comment]
The specific reason for doing this is to handle resizing scenarios properly, so that any existing references to DXGI backbuffer resources are severed before I re-recreate them.

**Comment by aaronstackpole** [comment]
Thanks, Mark. I think I figured it out, the point I was trying to make was do I need to execute those commands on the device context if it's a newly instantiated device context object generated by the factory?
