### ISSUE TITLE
CreatureTexture2D failed in DirectX Win32 Game  template.

### ISSUE THREAD

**Issue by ryancheung** [walbourn/directx-vs-templates#54]
Followed the [doc](https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-resources-textures-create) and attempted to create a `D3D11Texture2D` in the Win32 Game template, but it just fail:
1. It just crash with `0x00007FF8CBDC478C (KernelBase.dll) (Direct3D Win32 Game1.exe 中)处有未经处理的异常: 0x0000087A (参数: 0x0000000000000001, 0x000000751DAFC4B0, 0x000000751DAFE280)。` at `m_deviceResources->GetD3DDevice()->CreateTexture2D(&desc, NULL, &pTexture)`
2.  Comment out `creationFlags |= D3D11_CREATE_DEVICE_DEBUG;` then receive `E_INVALIDARG One or more arguments are invalid.` hr error

Repro: https://github.com/ryancheung/DirectX-Win32-Repro
OS: Windows 10/11
GPU0: Intel UHD Graphics 630
GPU1: NVIDIA GeForce GTX 1060

I'm stucking on getting started with DirectXTK for hours as a newbie, please help!

EDIT: It works in Release build

**Comment by ryancheung** [comment]
After force enable debug layer with d3dconfig tool, I got there error: D3D11 ERROR: ID3D11Device::CreateTexture2D: SampleDesc.Quality specifies invalid value -858993460. For 1 samples, the current graphics implementation only supports SampleDesc.Quality less than 1. <-- if 0 is shown here for Quality, this means the graphics implementation doesn't support 1 samples at all. Use CheckMultisampleQualityLevels to detect what the graphics implementation supports. 

So I forgot zero out `D3D11_TEXTURE2D_DESC` , `D3D11_TEXTURE2D_DESC desc = {};` fixed everything. Damn it.

**Comment by walbourn** [comment]
Zero-filling those DESC structures is a good habit. You could use the ``CD3D11_TEXTURE2D_DESC`` helper as well.
