### ISSUE TITLE
Include Props File?

### ISSUE THREAD

**Issue by ghost** [walbourn/directx-vs-templates#55]
I've been using .props files for project configuration these days, I typically start from a purely empty project and then apply a props file that sets language, rules, application type, include folders, library dependencies, and so forth. I mostly derived these settings by extracting them from these templates, but I find it is a much better way to manage project properties without having to go through the process of exporting a template file for the project. Then again, my engine does all of the window instantiation in the library, so the main() in my application is literally just loading the engine core class and running a basic while loop, not even MSG pump. Anyway, props files are really handy, would be a nice-to-have for Visual Studio users
[ClayEngineClientCore.props.txt](https://github.com/walbourn/directx-vs-templates/files/8366982/ClayEngineClientCore.props.txt)

![image](https://user-images.githubusercontent.com/8165121/160505179-b1b148be-7214-4745-8d4a-a6d447f6dfe0.png)

Thanks for consideration!

**Comment by walbourn** [comment]
Thanks for the feedback. For the VCXPROJ files I keep them simple since the template wizard creates the VCXPROJ files and the addition of extra props files is a 'non-standard' part of the project setup. I agree for 'real' projects this is easier to maintain.
