### ISSUE TITLE
Error when opening Direct3DUWPGame.vcxproj in VS2022 17.2.1

### ISSUE THREAD

**Issue by JayDeezus** [walbourn/directx-vs-templates#57]
Getting this error when I try to open the project in VS 2022. Looks like there's some kind of plain text that's not being recognized in the project file. 
![image](https://user-images.githubusercontent.com/47218690/169196146-511ef03a-4f30-49ce-99a7-7d157ddefdfd.png)

**Comment by walbourn** [comment]
Please attach the VCXPROJ file you are having problems with to this issue.

Thanks.

**Comment by JayDeezus** [comment]
Sorry about not getting back to you quickly on this. Since I posted this a VS update was released and I am now running on 17.2.2. I'll put the vcxproj up in a few moments.

**Comment by JayDeezus** [comment]
The error that's now showing up in VS2022 17.2.2: 
![image](https://user-images.githubusercontent.com/47218690/171196288-5af07ac7-28e7-4721-99cb-a7eb1df99b93.png)

**Comment by JayDeezus** [comment]
Additionally, versions of stuff installed on the machine from which I am attempting to open the file:

> Microsoft Visual Studio Community 2022
> Version 17.2.2
> VisualStudio.17.Release/17.2.2+32519.379
> Microsoft .NET Framework
> Version 4.8.04084
> 
> Installed Version: Community
> 
> Visual C++ 2022   00482-90000-00000-AA411
> Microsoft Visual C++ 2022
> 
> .NET Core Debugging with WSL   1.0
> .NET Core Debugging with WSL
> 
> ASP.NET and Web Tools 2019   17.2.389.42256
> ASP.NET and Web Tools 2019
> 
> Azure App Service Tools v3.0.0   17.2.389.42256
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools   17.2.389.42256
> Azure Functions and Web Jobs Tools
> 
> C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> CodeMaid   12.0
> CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Cookiecutter   17.0.22089.1
> Provides tools for finding, instantiating and customizing templates in cookiecutter format.
> 
> Linux Core Dump Debugging   1.0.9.32408
> Enables debugging of Linux core dumps.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Node.js Tools   1.5.40404.3 Commit Hash:dd524a7d0ee653de8b7b32a93ca22f2d57cd2419
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   6.2.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> Python - Django support   17.0.22089.1
> Provides templates and integration for the Django web framework.
> 
> Python - Profiling support   17.0.22089.1
> Profiling support for Python projects.
> 
> Python with Pylance   17.0.22089.1
> Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
> 
> Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
> Provides languages services for ASP.NET Core Razor.
> 
> Rewrap Extension   1.0
> Re-wraps comments and other text
> 
> SQL Server Data Tools   17.0.62204.01010
> Microsoft SQL Server Data Tools
> 
> Test Adapter for Boost.Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> Test Adapter for Google Test   1.0
> Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
> 
> TypeScript Tools   17.0.10418.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual C++ for Linux Development   1.0.9.32408
> Visual C++ for Linux Development
> 
> Visual F# Tools   17.1.0-beta.22253.3+058e7a7e597a02c129f38742f250a4b212da9ee3
> Microsoft Visual F# Tools
> 
> Visual Studio IntelliCode   2.2
> AI-assisted development for Visual Studio.
> 
> Visual Studio Tools for Unity   17.2.3.0
> Visual Studio Tools for Unity

**Comment by JayDeezus** [comment]
I think it has something to do with that `$(TargetPlatformVersion)` string in the vcxproj file. I assume this is meant to be translated to some actual value, but I don't know if that's supposed to happen when I open the vcxproj as a consumer of the repo, or if that's something that you need to run a script for on your end as the producer.

HTH

**Comment by walbourn** [comment]
Note that I do have a PowerShell script for instantiating the templates for CMake without using VS integration.
