### ISSUE TITLE
[Project Template] add WindowsAppSDK project templates

### ISSUE THREAD

**Issue by Demonese** [walbourn/directx-vs-templates#59]
Is it possible to add project templates for WindowsAppSDK? I think this helps developers get started with it.

**Comment by ewdlop** [comment]
WinUI3 please!

**Comment by walbourn** [comment]
These templates are all intended to be "full-screen/immersive" experiences a.k.a. like a game. This allows the same basic structure to work for Win32 desktop, UWP, and Xbox.

WinUI3, WPF, XAML, and DirectX+XAML are therefore out of scope for this repository.

A good place to request this kind of deved material for WinUI3 would be their [GitHub](https://github.com/microsoft/microsoft-ui-xaml) project.
