### ISSUE TITLE
Template code crashes on TDR (dxcap -forcetdr)

### ISSUE THREAD

**Issue by anup-das** [walbourn/directx-vs-templates#60]
App generated using d3d12game_uwp_cppwinrt_dr template crashes on TDR event (dxcap -forcetdr).

Actually, I first observed the problem in my app that uses d3d11game_uwp_dr template and has some additional drawing code (Rotating 3D cube from the VS template). I resolved it by adding m_d3dContext->ClearState() followed by m_d3dContext->Flush() calls in DeviceResources::HandleDeviceLost() function as hinted by the DirectX debug layers.  It would be nice to have these calls in the template

Thereafter I checked the D3D12 default template generated code with no additional code. On my system the app is unable to survive the TDR event and crashes.

**Comment by walbourn** [comment]
What version of Windows are you using? Also, are you using a 'hybrid graphics' system with Intel+a GPU or something else?

**Comment by anup-das** [comment]
Here is the DxDiag report generated on my system.
[DxDiag.txt](https://github.com/walbourn/directx-vs-templates/files/9087505/DxDiag.txt)

**Comment by anup-das** [comment]
I just generated a test app enabled debugging in VS 2022 and ran dxcap -forcetdr from an elevated prompt.  Here is the exception message, Output Window logs and Call stack trace (at the very end
[debug logs.txt](https://github.com/walbourn/directx-vs-templates/files/9087576/debug.logs.txt)
)

**Comment by walbourn** [comment]
Using ``m_d3dContext->ClearState()`` followed by ``m_d3dContext->Flush()`` in the LostDevice handler can be an option, but it's definitely a bit of a hack.

For robust "Lost Device" handling you really want to have the explicit clean-up of all Direct3D resource objects there.
