### ISSUE TITLE
WindowSizeChanged needs UpdateColorSpace?

### ISSUE THREAD

**Issue by BMarques** [walbourn/directx-vs-templates#61]
Hello, as the title says, is the UpdateColorSpace needed in WindowSizeChanged? I tried it without and it works as well as expected, The HDR works well and Win + Alt + B also works well. Unless there's a reproduction scenario that I'm not aware of? 

I'm referring to this part:

```
if (m_outputSize.right == width && m_outputSize.bottom == height)
{
    // Handle color space settings for HDR
    UpdateColorSpace();

    return false;
}
```

**Comment by walbourn** [comment]
This is present along with ``OnWindowsMoved`` to deal with multiple monitor set ups with a mix of HDR and SDR monitors.
