### ISSUE TITLE
Question: ColorSpace value of HDR swap chain for composition (XAML)

### ISSUE THREAD

**Issue by anup-das** [walbourn/directx-vs-templates#64]
To update colorspace of the swap chain, the template code detects HDR display associated with the app based on HWND (Win32) or CoreWindow (UWP) 

Comment in code...
// To detect HDR support, we will need to check the color space in the primary DXGI output associated with the app at this point in time

Association is checked via bounds of app window and its intersection area with the desktop display area.

What should an XAML app that uses CreateSwapChainForComposition  do ?  On what criteria can the XAML app decide the colorspace of swap chain ?  i.e whether the app (DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020) or the system (DXGI_COLOR_SPACE_RGB_FULL_G10_NONE_P709) creates the HDR10 signal

BTW I am using DirectX 11

Thanks in advance,
Anup

**Comment by walbourn** [comment]
Thanks for the follow up. I don't do much with XAML+DirectX scenarios myself.
