### ISSUE TITLE
VS 2017 templates fail unless VS 2015 also installed

### ISSUE THREAD

**Issue by walbourn** [walbourn/directx-vs-templates#7]
> Moved from [DirectXTK](https://github.com/Microsoft/DirectXTK/issues/85)

I am unable to use the templates from the Getting Started Guide  [VS 2013 / VS 2015 / VS 2017 VSIX ](https://github.com/walbourn/directx-vs-templates/raw/master/VSIX/Direct3DUWPGame.vsix)

When attempting to create a new project using the templates I get an error dialog:

    Error: this template attempted to load component assembly 
    'Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0,
    Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. For more 
    information on this problem and how to enable this template, 
    please see documentation on Customizing Project Templates.

I assume it's simply just looking for a certain version of the component assembly, I think Version 15 would be for 2017. I'm not sure how to get in there and actually edit the template by hand myself.

**Comment by walbourn** [comment]
A workaround for this is to edit ``C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe.config`` and add to the ``<assemblyBinding>`` section:

        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.Universal.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0" newVersion="15.0.0.0"/>
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.WinRT.TemplateWizards" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="14.0.0.0" newVersion="15.0.0.0"/>
        </dependentAssembly>

**Comment by unreal5** [comment]
Yes, solve my problems, thx!非常感谢，解决了我的问题！

**Comment by walbourn** [comment]
Note that this is fixed in [Visual Studio 2017 15.3 Developer Preview 2](https://www.visualstudio.com/vs/preview/).

**Comment by nait123321** [comment]
Till now gives out an error, tried and on VS17 and on VS17
http://i.imgur.com/nOXDgxK.png

**Comment by walbourn** [comment]
If you are not using a VS 2017 Developer Preview build, then the VSIX package needs you to have VS 2015 installed as well as VS 2017.

**Comment by nait123321** [comment]
Thanks for the quick response. Unfortunately, due to my inattention, I made a mistake in the last message. After installing Preview and a couple of SDK re-installs - it worked.

**Comment by walbourn** [comment]
The VS 2017 (15.3) update is now [available](https://blogs.msdn.microsoft.com/visualstudio/2017/08/14/visual-studio-2017-version-15-3-released/).

**Comment by joneschrisan** [comment]
This has now been updated and added to VS 2017 as standard but you now get a new error. 

--------------------------
Package Installation Error

Could not add all required packages to the project. The following packages failed to install from 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages':

Microsoft.NETCore.UniversalWindowsPlatform.5.1.0 : Unable to find version '5.1.0' of package 'Microsoft.NETCore.UniversalWindowsPlatform'.
--------------------------

After clicking the only option "OK" You still have the errors but build always fails

**Comment by walbourn** [comment]
The VS 2019 version of the issue is covered [here](https://github.com/walbourn/directx-vs-templates/issues/25) and has been reported to the [VS Team](https://developercommunity.visualstudio.com/content/problem/572125/visual-studio-2019-doesnt-handle-14000-assembly-re.html).

**Comment by trojanfoe** [comment]
Thanks, that did the trick!

**Comment by KeyC0de** [comment]
This is happening to me on latest Visual Studio 2017 version, after trying to create a new "DirectX Win32 Game" project using the template and .vsix file downloaded here https://github.com/walbourn/directx-vs-templates/raw/master/VSIX/Direct3DUWPGame.vsix. I'm following this tutorial to the letter: https://github.com/microsoft/DirectXTK/wiki/The-basic-game-loop.

I don't have Visual Studio 2015, or 2019 installed.
