### ISSUE TITLE
C++/WINRT: beware where calling CoreWindow::GetForCurrentThread().Activate();

### ISSUE THREAD

**Issue by alessiot89** [walbourn/directx-vs-templates#8]
When debugging, placing a breakpoint on the Run() method, caused the application shut-down after few (3-5) seconds, like if it went in time-out.
Placing the CoreWindow::GetForCurrentThread().Activate() call in the Run() method (like at the beginning of it) seems to solve the problem.

According to MSDN the Visual Studio debugger should prevent this, however that's related to C++/CX environment only.
I am not sure if this is related to the C++/WINRT or it is an intended behaviour.
I am posting this here because I started playing with C++/WinRT looking at the d3d12 game UWP C++/WinRT template.

**Comment by walbourn** [comment]
I was able to repro this on both ``/ZW`` and C++/WinRT using VS 2017, but not with VS 2015 Update 3. I suspect this is an issue with VS 2017 generally and not specific to the template or C++/WinRT.
